### ISSUE TITLE
Miss input output boundary: One big problem of clean architecture

### ISSUE THREAD

**Issue by ChloeH88** [CSC207-UofT/course-project-realmatrix#10]
**I think this is one of the issues with highest priority. I will deal with it in these two days.**

According to clean architecture diagram <img width="834" alt="Screen Shot 2021-11-12 at 8 36 51 PM" src="https://user-images.githubusercontent.com/90373791/141468323-29db35cf-865e-4a7d-b761-e4b635b49ab0.png">, and Piazza posts (https://piazza.com/class/kt4hlydpsym1bz?cid=819  AND  https://piazza.com/class/kt4hlydpsym1bz?cid=769), we should create Input & Output Boundary interfaces. 

To be more specific, all use case classes should implement input boundaries, and controllers should only interact with those boundaries, i.e. controllers have no idea about how use case classes are implemented. 

See an example: <img width="912" alt="Screen Shot 2021-11-12 at 8 36 23 PM" src="https://user-images.githubusercontent.com/90373791/141468255-f0eba354-7bdb-4c2d-8f1a-fcd16befac3e.png">

**Comment by xingl213** [comment]
We likely won't have time to completely fix this for Phase 1 but we can definitely fix this later. Let me know if you need help.

**Comment by ChloeH88** [comment]
Yifan Zhao and I had completely most input boundaries and output boundaries. Input/output boundaries and controllers for review and learn need to be implemented in phase 2.
