### ISSUE TITLE
List of things we should do/modify in phase 2

### ISSUE THREAD

**Issue by ChloeH88** [CSC207-UofT/course-project-realmatrix#13]
Add to this list of tasks. Leave a comment below and remove the task once you completed it.

Functionality completion

- GUI interacts `ProgramStateController` when users enter/leave a pack, edit a card/ leave editing.
- GUI **(Note, people who implemented GUI may find some backend issues, like presenter result is not suitable, etc)** Feel free to solve those backend issues yourself or raise them. @JC605 @Runshi-Yang 
- `constants`: Define our own `Exception` class instead of throwing general Exception.
- `constants`: Add `proficiency` attribute for card into `constants`.
- Implement new features
- Improve learn and review algorithm

Refactoring

- Refactor and deal with code smells
- Documentation

Design

- Implement input/output boundaries for review/learn functionalities in more details.
- Implement other useful design patterns

**Comment by xingl213** [comment]
completed "gateway: Change return type of initialLoad from userManager to something else, maybe a hash map of username to password." in commit 556d2b50549a2bd2b98495206d7a25df05208eb5

**Comment by xingl213** [comment]
completed "Remove id attribute for card/pack/user. id is useless because our precondition is we have unique card term, pack name, and username." in commit dbee210256c1ddf0587b3b824dc3416b56f3bddb

**Comment by ChloeH88** [comment]
For saving data, called `write` methods in controllers when user registers (write user), add pack (write pack), and add card (write card).
**Question**: how to write into database when user changes information? For example, when user changes a  card's term.
It seems we need to add `overwrite` methods or something like that in gateway.

**Comment by ChloeH88** [comment]
Completed "controller or manager should call on methods in DataInOut (note using dependency inversion) to load data.
